include:
- project: 'sast'
  ref: 2.3.4
  file: 'sast.dotnetmono.gitlab-ci.yml'

default:
  tags:
    - aws-k8s

stages:
    - sast
    - lint
    - checksum
    - sonarqube
    - sonarbadge
    - deploy

variables:
  API_KEY: OGUzYzJkNWMtMzA5NS00MzIyLWIxNWYtOWZhODg1NDc3M2Fk
  NN_SECRET_DETECTION_RULESETS_REPO_REF: "SDP-2527"


deploy_aws:
  image: python:3.8
  stage: deploy
  when: manual
  before_script:
    - pip3 install awscli --upgrade
    - pip3 install aws-sam-cli --upgrade
  script:
    - sam build
    - sam package --output-template-file packaged.yaml --s3-bucket #S3Bucket#
    - sam deploy --template-file packaged.yaml --stack-name gitlab-example --s3-bucket #S3Bucket# --capabilities CAPABILITY_IAM --region us-east-1
